# ALL THE SETUP OF THE PYLINT


# STATIC ONLY

# Input of the analysis containing parsable python files
input_folder: data/datasets/exp_v08/files_selected
# input_folder: data/datasets/sample_dataset/files_selected


# output_folder: where to store the individual csv of the metrics
output_folder: data/datasets/exp_v08/pylint
# output_folder: data/datasets/sample_dataset/pylint

metrics_to_compute:
  - all

# analyze only a subset of files
subset_files_to_analyze:
  - ahmed154_73ece9.py
  - task_0f414b.py
  - test_sdk_352e8e.py
  - test_circuit_load_from_qasm_bf30ab.py
  - test_circuit_qasm_ae5268.py
  - test_decompose_78559e.py
  - test_structure_aaba85.py
  - tutorial03_quantumoperations_061e13.py
  - test_unroll_3q_or_more_7bf310.py
  - xqiskit_test_ab1d81.py
  - b24_hadamard_solutions_2ba19d.py
  - example_qiskit_conditional_5ae7f6.py
  - example_qiskit_conditional_67fb51.py
  - example_qiskit_conditional_78732d.py
  - gates_20overview_44ffd3.py
  - fourier_transform_ncb_45a87d.py
  - mgr_11_incrementer_as_instruction_6d53c5.py
  - constante_1_00_d02e10.py
  - ex1_a7614b.py
  - measurement_postulate_single_qubit_f_fb7a34.py
  - measurement_tests_fdc8b4.py
  - quantum_encoding_5a7eeb.py
  - qxq_ylc_lab_5_student_e32900.py
  - superpositions_26c0f1.py
  - a00_qiskit_introduction_checkpoint_78fe1f.py
  - functionsjozsa_428a2d.py
  - representing_qubit_states_610048.py
  - tabula_rasa_768589.py
  - test_compiler_907f66.py
  - test_compiler_af868d.py
  - test_mapper_217a32.py
  - balanceada_2_48d67f.py
  - balanceada_3_11881b.py
  - a00_qiskit_introduction_1ba1af.py
  - a00_qiskit_introduction_79143b.py
  - aatoms_of_computation_ed6fac.py
  - atoms_computation_01fe8e.py
  - basics_64c7b2.py
  - deutsch_jozsa_s_20functions_b84a95.py
  - err_10214c.py
  - ex1_98892e.py
  - hadamard_b2fac2.py
  - hello_b14c35.py
  - herrtestcomptimetiffoli_cf1dac.py
  - qiskit_qae_e2636d.py
  - montgomery_modular_multiplication_593bfe.py
  - qrpgcg_cd84f9.py
  - quantum_e3f4e0.py
  - qubitstates_903372.py
  - test_qasm_simulator_edd048.py
  - rsa_breaker_4_bit_0f27ff.py
  - qubits_d78ad0.py
  - qubits_intro_974f92.py
  - sandbox_e52934.py
  - shorbreaker_5299e4.py
  - test_circuit_to_dag_5333cb.py
  - test_qasm_simulator_682153.py
  - test_stochastic_swap_89a6ef.py
  - 02_measurements_and_mixed_states_qiskit_ee25f6.py
  - example_d675c9.py
  - error_correction_repetition_code_e94ab1.py
  - neoh2evo_28b965.py
  - h2evo_6bb46f.py
  - test_mc_gate_13ba80.py
  - transpiled_stabilizer_test_7be7ce.py
  - h2evoqlm_f7e7b5.py
  - shor_df608f.py
  - matchgate_tools_mudground_checkpoint_a852d9.py
  - mnist_dd2c4f.py
  - polarization_20rotator_20angle_25374b.py
  - qrng_9498d5.py
  - bell_states_example_55fd07.py
  - example_1_c6d971.py
  - interferibmc_c22d6b.py
  - main_2f60d4.py
  - quantum_entanglement_f902fe.py
  - test_parse_counts_0953d6.py
  - n_qubit_grovers_algorithm_ff6131.py
  - qiskit_c50734.py
  - qrng_09be03.py
  - code_12fb50.py
  - ghz_ca5e66.py
  - ghz_7af332.py
  - groverfuncs_9232ea.py
  - real_system_c4c34f.py
  - source_59a0eb956a0d4e6b8720f272136f2799_9b8ba7.py
  - source_948f90de9947418289b220bd2e61caa3_caae3b.py
  - one_qubit_fb6117.py
  - python_quantum_number_generator_1_6_multi_qasm_76fe84.py
  - q04_qiskit_installation_and_test_7d0f02.py
  - quantum_key_distribution_e8abe3.py
  - quantum_random_pixel_generator_multi_qasm_bebc43.py
  - teleportation_07c3ca.py
  - ch_3_28325b.py
  - quantumteleportation_2823d6.py
  - quantumteleportationprotocol_7da521.py
  - task_3_4b4e03.py
  - q02_417981.py
  - quantum_key_distribution_875841.py
  - quantum_pixel_generator_multi_qasm_fractional_variable_d8275b.py
  - quantum_random_pixel_generator_multi_qasm_complete_8582ba.py
  - quantum_random_pixel_generator_multi_qasm_variable_1f937f.py
  - quantum_teleport_4f22f3.py
  - quantum_teleportation_1881c2.py
  - quantum_teleportation_9276a1.py
  - teleportation_a12212.py
  - teleportation_practice_4ae2ea.py
  - quntum_204_dec_2005_202020_206_2042_20am_16e278.py
  - single_qubit_01e1c7.py
  - task_2_4f46b2.py
  - teleportation_50c827.py
  - teleportation_8f1eaf.py
  - the_20quantum_20teleportation_20algorithm_c014d5.py
  - two_qubit_4cff15.py
  - 12_quantum_key_distribution_checkpoint_4165fd.py
  - correlations_31df66.py
  - demo3_quantum_teleportation_5b8be6.py
  - electroquantum_39cf94.py
  - encrpytion_e53b97.py
  - hardware_3936ea.py
  - main_20code_20soccer_20quantum_20predicter_a83463.py
  - quantumdice_bc7351.py
  - hello_qiskit_e84c92.py
  - easy_qnn_0305db.py
  - 4atoms_of_computation_332679.py
  - a03_deutsch_algorithm_solutions_checkpoint_cd1511.py
  - day_203_20universality_69a67f.py
  - jakoyhtalot_algoritmit_8daaee.py
  - qgates_4e7d74.py
  - qkd_dashboard_greesan_5bf1cb.py
  - quantum_match_filtering_paper_replication_cdc179.py
  - test_code_91c4dd.py
  - quantum_walker_cbff5a.py
  - test_identifiers_6ec4a8.py
  - test_iqm_backend_9dfa5b.py
  - z_gate_d06a00.py
  - test_circuit_combine_extend_a76ce4.py
  - test_output_bd6143.py
  - test_quantumprogram_6f378f.py
  - 07_variational_circuits_f6a719.py
  - circuit_d01243.py
  - demo_6973fd.py
  - dmft6_3cfa29.py
  - gateset_4ffe74.py
  - deutschjozsa_5a9218.py
  - quantumcircuit_20withoutmeasure_e133f5.py
  - benchmark_72ca3d.py
  - 3_more_circuit_identities_checkpoint_986a09.py
  - test_u_gate_940648.py
  - multiple_qubits_entangled_states_d1b18b.py
  - multiplier_5c47de.py
  - qiskit_and_ibmq_ad1bdd.py
  - test_qulacs_converter_ec6aa2.py
  - test_sdg_gate_56b97a.py
  - quantum_walks_project_329d10.py
  - rotation_95ca93.py
  - test_qiskit_738074.py
  - wrapper_iae_fab9d4.py
  - challenge4_circuitdecomposition_a80a1d.py
  - decomposed_a7ee15.py
  - draft_qnn12_0e9c87.py
  - ex2_fr_dc4911.py
  - inverse_dcf9ae.py
  - lab_2_malihe_e61048.py
  - 4_qbits_decoherence_9bbc1f.py
  - bit_flip_code_f40402.py
  - discrete_solver_7f2f57.py
  - 01_classical_and_quantum_probability_distributions_411e21.py
  - helper_functions_a521e2.py
  - energyrelaxation_230ca7.py
  - phase_flip_code_4072b2.py
  - t1_3fa19f.py
  - t2_ramsey_2e0f5a.py
  - unitary_simulator_25e259.py