# ALL THE SETUP OF THE QSMELL


# STATIC ONLY

# Input of the analysis containing parsable python files
input_folder: data/datasets/qsmell_benchmark/original_programs

# output_folder: where to store the individual csv of the metrics
output_folder: data/datasets/qsmell_benchmark/qsmell

# metrics: each must have a .py file with the same name
# and should expose a method compute_metric(ast, output_file_path)
# a new subfolder will be created for each metric
metrics_to_compute:
  - NC
  - LPQ

